### GET All Books (L)
GET http://localhost:8080/books

### POST Create Book (L)
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Dune",
  "author": "Frank Herbert",
  "year": 1965
}

### GET Book by ID (L)
GET http://localhost:8080/books/6832b599e40fddd9a6a5c348

### PUT Update Book (L)
PUT http://localhost:8080/books/6832b599e40fddd9a6a5c348
Content-Type: application/json

{
  "title": "Dune (Updated)",
  "author": "Frank Herbert",
  "year": 1966
}

### DELETE Book (L)
DELETE http://localhost:8080/books/6832b599e40fddd9a6a5c348

###

### GET All Books (R)
GET https://lesson5-books-api.onrender.com/books

### POST Create Book (R)
POST https://lesson5-books-api.onrender.com/books
Content-Type: application/json

{
  "title": "Dune",
  "author": "Frank Herbert",
  "year": 1965
}

### GET Book by ID (R)
GET https://lesson5-books-api.onrender.com/books/6832b599e40fddd9a6a5c348

### PUT Update Book (R)
PUT https://lesson5-books-api.onrender.com/books/6832b599e40fddd9a6a5c348
Content-Type: application/json

{
  "title": "Dune (Updated)",
  "author": "Frank Herbert",
  "year": 1966
}

### DELETE Book (R)
DELETE https://lesson5-books-api.onrender.com/books/6832b599e40fddd9a6a5c348
